[2020-10-16 10:54:51,299] [log.py|__console] [line:45] INFO    : 当前执行测试用例ID-> test_login001.5 ; 测试点-> 13511112222
[2020-10-16 10:54:56,253] [log.py|__console] [line:45] INFO    : 检查点-> 用户名或密码有误，请重新输入或找回密码
[2020-10-16 10:54:56,491] [log.py|__console] [line:45] INFO    : 异常登录，返回实际结果是->: 用户名或密码有误，请重新输入或找回密码
